### PR TITLE
Adds caller check for 'FireOracle.respond()'

### PR DESCRIPTION
**Pull request by rapidddenis**

### CODE REVIEW

**Comment by doerfli** [comment]
I also thought about adding this, but finally decided against it to keep it simpler. The Sandbox is a playground example and without the modifier it's just easier to interact with it (less typing `{from: ..}`). 
Maybe it should be added as comment (for completeness as it should be bete normally) and also put a note there why its been commented out.

**Comment by doerfli** [comment]
@rapidddenis can you please sign the CLA agreement as indicated by the bot comment above. thanks.

**Comment by rapidddenis** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by doerfli** [comment]
recheck

**Pull request closed without merging**
